---
title: "Report"
author: "Andrew Liu, Carol Wang, Luna_Lan, Sarah Hu, Ziyi An"
date: "2/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem Domain

Recently, influenced by COVIS-19 pneumonia, Chinese state-backed importers of natural gas are examining if they can provisionally halt contracts for the supercooled fuel, as the COVIS-19 outbreak depresses energy demand in the world’s second-largest economy. This temporary cancellation of contracts has created headaches for natural gas suppliers and made them concerned about the future.

Therefore, our group will discuss the correlation between spreading of COVIS-19 and the price of natural gas in the final project. This topic is meaningful because natural gas is one of the most important resources in the world and its market is closely tied to the global economy and to our daily life. The data of COVIS-19 virus spreading is from the World Health Organization and the data of natural gas prices is from datahub. They are all credible and sources. 

Only very basic statistical knowledge will be involved in our report and it should be straightforward for every reader!

### The List of Questions Covered:
1. Based on the data set, does the number of coronovirus pneumonia cases confirmed have no effect on the price of natural gas?

Since we have many features describing the spreading of coronavirus, we need to find out which feature could have the most direct impact on the price of natural gas.

2. 
